#!/usr/bin/env python3
"""
run_quantum_state_input.py - Paper 6 main experiment.

QRC vs classical reservoirs on a HILBERT-SPACE INPUT task.  The input
is itself a q-qubit quantum state |psi_t> generated by a fixed
Hamiltonian trajectory; the classical baseline cannot encode |psi_t>
into a feature vector without first burning shots on shadow tomography.
QRC uses the same shot budget to do encoding + reservoir mixing
simultaneously.

Methods (matched shot budget M = shots_per_qubit * q per timestep):
  - QRC_state_injection : on each step, |psi_t> is prepared on the
       first n_in reservoir qubits; rest in |0>.  Evolve under H_TFIM(q)
       for time tau.  Sample M shots, extract local Paulis
       (<Z_i>, <Z_i Z_j>).
  - Classical_shadows + RFF : on each step, perform M random Clifford
       shadow snapshots on |psi_t>; estimate local Paulis from shadows.
       Use as features for windowed RFF.
  - Cheating_classical + RFF : exact local Paulis on |psi_t> (no shot
       noise).  Upper bound for any classical method using local Paulis.
  - ESN_matched : ESN at matched N on the cheating Pauli features.

Target functionals (paper 6 cleanest target = 4-body Pauli):
  - <X_0 X_1 X_2 X_3> on the input state at horizon t+k
       Shadow shot cost for k-body observables grows as 3^k, so QRC's
       fixed sigma ~ 1/sqrt(M) should beat shadows badly at q >> n_in.

Outputs:  results/quantum_state_input/<tag>/summary.json + plots
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import warnings
from pathlib import Path

import numpy as np
from scipy import linalg as sla

warnings.filterwarnings("ignore")

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

# Reuse Pauli + Hamiltonian + Heisenberg builders from paper-5 script
from run_quantum_input_experiment import (
    I2, X, Y, Z, PAULI,
    pauli_string, single_site, two_site,
    heisenberg_chain_hamiltonian, xxz_chain_hamiltonian,
    build_target_hamiltonian, evolve_states,
    tfim_hamiltonian, scrambling_hamiltonian,
    _apply_single_qubit_gate,
    make_esn, esn_run, rff_features,
    ridge_solve, windowed_features, feature_gram_condition,
    _eval_windowed_no_window,
)


# ---------------------------------------------------------------------------
# State-injection QRC
# ---------------------------------------------------------------------------

def make_state_injection_qrc(n_qubits: int, n_in: int, H_reservoir: np.ndarray,
                                tau: float = 1.0,
                                shots_per_qubit: int = 1024,
                                rng: np.random.Generator | None = None):
    """Build a QRC with state-injection input mode.

    At each timestep:
      1. Receive a 2^n_in-dim input state vector psi_in.
      2. Prepare on reservoir: |psi_in> tensor |0>^(q-n_in).
      3. Evolve full reservoir under H_reservoir for time tau.
      4. Sample M = shots_per_qubit * q shots.  Extract local Paulis
         (<Z_i>, <Z_i Z_j>), D = q(q+1)/2 features.
    NO recurrence across timesteps (input state is re-prepared each step
    -- same constraint as the classical baseline; the only memory comes
    from windowing the features later, identical for both methods).
    """
    dim = 2 ** n_qubits
    q = n_qubits
    M = shots_per_qubit * q
    U_evolve = sla.expm(-1j * H_reservoir * tau)
    if rng is None:
        rng = np.random.default_rng(0)

    idx = np.arange(dim, dtype=np.uint32)
    bits = ((idx[:, None] >> np.arange(q)[::-1]) & 1).astype(np.int8)
    signs = (1 - 2 * bits).astype(np.float64)
    iu, ju = np.triu_indices(q, k=1)
    pair_signs = signs[:, iu] * signs[:, ju]

    dim_in = 2 ** n_in
    dim_rest = 2 ** (q - n_in)
    rest_init = np.zeros(dim_rest, dtype=complex); rest_init[0] = 1.0

    def step(psi_in: np.ndarray) -> np.ndarray:
        """Inject |psi_in> on first n_in qubits, evolve, sample, return features."""
        psi_full = np.kron(psi_in, rest_init)
        psi_full = U_evolve @ psi_full
        p = np.abs(psi_full) ** 2
        s = p.sum()
        if s > 0:
            p = p / s
        counts = rng.multinomial(M, p).astype(np.float64)
        w = counts / M
        Z_vals  = w @ signs
        ZZ_vals = w @ pair_signs
        return np.concatenate([Z_vals, ZZ_vals])

    return step, q * (q + 1) // 2


# ---------------------------------------------------------------------------
# Classical shadow tomography
# ---------------------------------------------------------------------------

# Single-qubit Clifford rotations that map computational basis to X/Y/Z basis.
# We use the 3-basis (Pauli) shadow scheme (simplest, well-known).
# Rotation that maps measurement basis to X-eigenstates: H (Hadamard)
# To Y-eigenstates: HS^dag (or equivalently S H), depending on convention.
# To Z-eigenstates: identity.
H_GATE = (1.0 / np.sqrt(2)) * np.array([[1, 1], [1, -1]], dtype=complex)
S_DAG = np.array([[1, 0], [0, -1j]], dtype=complex)
HSDAG = H_GATE @ S_DAG  # rotates Y eigenstates to Z basis


def _rotated_probabilities(psi: np.ndarray, n: int,
                              basis_pattern: tuple[int, ...]) -> np.ndarray:
    """Probability distribution of measuring |psi> in basis given by
    basis_pattern, a length-n tuple of (0=X, 1=Y, 2=Z)."""
    BASIS_GATES = [H_GATE, HSDAG, I2]
    psi_rot = psi
    for qubit in range(n):
        b = basis_pattern[qubit]
        if b != 2:                      # Z = identity rotation
            psi_rot = _apply_single_qubit_gate(psi_rot, n, qubit, BASIS_GATES[b])
    p = np.abs(psi_rot) ** 2
    s = p.sum()
    return p / s if s > 0 else p


def shadow_snapshots_estimate(psi: np.ndarray, n: int, M: int,
                                 rng: np.random.Generator,
                                 want_features: list[tuple[str, ...]]
                                ) -> np.ndarray:
    """Estimate Pauli expectations from M Pauli-shadow snapshots of |psi>
    using the Huang-Kueng-Preskill (2020) single-qubit-Clifford protocol.

    FAST VERSION: shots are grouped by basis pattern.  Cost is
    O(3^n * 2^n * n + M * n) instead of O(M * 2^n * n) -- ~80x speedup
    for n=4, M=7168.
    """
    PAULI_CODE = {"X": 0, "Y": 1, "Z": 2}

    # Sample M basis patterns at once.
    bases_M = rng.integers(0, 3, size=(M, n), dtype=np.int8)   # (M, n)
    # Pack each pattern into a single integer key in [0, 3^n).
    keys = np.zeros(M, dtype=np.int64)
    for q_ in range(n):
        keys = keys * 3 + bases_M[:, q_]
    # Unique patterns + counts; sort by key for grouped processing.
    order = np.argsort(keys, kind="stable")
    keys_sorted = keys[order]
    bases_sorted = bases_M[order]
    # Find group boundaries.
    boundaries = np.flatnonzero(np.diff(keys_sorted)) + 1
    starts = np.concatenate([[0], boundaries])
    ends   = np.concatenate([boundaries, [M]])

    # We'll fill outcomes (M, n) in the SORTED order, then unsort.
    outcomes_sorted = np.zeros((M, n), dtype=np.int8)
    dim = 2 ** n
    bit_shifts = (n - 1 - np.arange(n)).astype(np.int64)
    for gi in range(len(starts)):
        s_, e_ = starts[gi], ends[gi]
        pattern = tuple(int(b) for b in bases_sorted[s_])    # all same in group
        p = _rotated_probabilities(psi, n, pattern)
        # Sample (e_ - s_) outcomes from this distribution via multinomial:
        # represent as a count vector over the 2^n outcomes, then expand to
        # a list of sample indices (faster than rng.choice per shot).
        counts = rng.multinomial(e_ - s_, p)
        # Build a flat array of sample integer indices respecting counts.
        sample_ints = np.repeat(np.arange(dim, dtype=np.int64), counts)
        rng.shuffle(sample_ints)            # randomize within the group
        # Unpack to bits, MSB-first.
        bits = ((sample_ints[:, None] >> bit_shifts) & 1).astype(np.int8)
        outcomes_sorted[s_:e_, :] = bits

    # Unsort to recover original shot order
    inv_order = np.empty_like(order); inv_order[order] = np.arange(M)
    outcomes = outcomes_sorted[inv_order]

    # +/-1 eigenvalues
    eig = (1 - 2 * outcomes).astype(np.float64)               # (M, n)

    out = np.zeros(len(want_features))
    for fi, feat in enumerate(want_features):
        pairs = [(feat[i], feat[i + 1]) for i in range(0, len(feat), 2)]
        kbody = len(pairs)
        match = np.ones(M, dtype=bool)
        prod_eig = np.ones(M, dtype=np.float64)
        for (lbl, site) in pairs:
            match &= (bases_M[:, site] == PAULI_CODE[lbl])
            prod_eig *= eig[:, site]
        contribs = np.where(match, (3.0 ** kbody) * prod_eig, 0.0)
        out[fi] = contribs.mean()
    return out


def make_shadow_extractor(n_in: int, shots_per_qubit_total: int,
                            q_reservoir: int,
                            rng: np.random.Generator,
                            include_2body: bool = True):
    """Build a feature extractor that, given psi_in (2^n_in-dim), runs
    Pauli-shadow tomography with the SAME total shot budget the QRC uses
    (M = shots_per_qubit_total * q_reservoir), and returns estimates of:
       <Z_i>, <X_i>, <Y_i>, and optionally all 2-body same-letter terms.
    Feature dim: 3*n_in + (3*n_in*(n_in-1)/2 if include_2body else 0)
    """
    M = shots_per_qubit_total * q_reservoir
    want = []
    for i in range(n_in):
        for p in ("Z", "X", "Y"):
            want.append((p, i))
    if include_2body:
        for i in range(n_in):
            for j in range(i + 1, n_in):
                for p in ("Z", "X", "Y"):
                    want.append((p, i, p, j))

    def step(psi_in: np.ndarray) -> np.ndarray:
        return shadow_snapshots_estimate(psi_in, n_in, M, rng, want)

    return step, len(want)


def make_cheating_classical_extractor(n_in: int, include_2body: bool = True):
    """Exact local Pauli features on |psi_in>, no shot noise."""
    want = []
    ops = []
    for i in range(n_in):
        for p in ("Z", "X", "Y"):
            want.append((p, i))
            ops.append(single_site(p, i, n_in))
    if include_2body:
        for i in range(n_in):
            for j in range(i + 1, n_in):
                for p in ("Z", "X", "Y"):
                    want.append((p, i, p, j))
                    ops.append(two_site(p, i, p, j, n_in))

    def step(psi_in: np.ndarray) -> np.ndarray:
        out = np.empty(len(ops))
        for k, O in enumerate(ops):
            out[k] = float(np.real(psi_in.conj() @ (O @ psi_in)))
        return out

    return step, len(want)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--n-input", type=int, default=5,
                    help="qubits of the input quantum state")
    p.add_argument("--n-qubits", type=int, default=8,
                    help="qubits in the QRC reservoir (>= n-input)")
    p.add_argument("--target-system", choices=["heisenberg", "xxz"],
                    default="heisenberg")
    p.add_argument("--target-seed", type=int, default=42)
    p.add_argument("--target-disorder", type=float, default=0.5)
    p.add_argument("--xxz-delta", type=float, default=0.5)
    p.add_argument("--n-steps", type=int, default=600)
    p.add_argument("--t-max", type=float, default=60.0)
    p.add_argument("--window", type=int, default=5)
    p.add_argument("--horizons", type=int, nargs="+", default=[1, 5, 20])
    p.add_argument("--n-seeds", type=int, default=3)
    p.add_argument("--train-frac", type=float, default=0.7)
    p.add_argument("--shots-per-qubit", type=int, default=1024)
    p.add_argument("--target-body", type=int, default=4,
                    help="body count k of the target Pauli string"
                          " (target = <X_0 X_1 ... X_{k-1}>)")
    p.add_argument("--out-dir", type=str,
                    default=str(ROOT / "results" / "quantum_state_input"))
    args = p.parse_args()

    assert args.n_input <= args.n_qubits, "n_input <= n_qubits"
    out_dir = Path(args.out_dir); out_dir.mkdir(parents=True, exist_ok=True)

    print(f"=== Paper 6 task: {args.n_input}-qubit input state -> "
            f"{args.n_qubits}-qubit reservoir ===")
    print(f"    target: {args.target_body}-body Pauli <X_0..X_{args.target_body-1}>"
            f" at horizons {args.horizons}")
    print(f"    shots = {args.shots_per_qubit * args.n_qubits} per timestep "
            f"(shared by QRC and shadows)")

    # ---- Generate input quantum-state trajectory ----
    H_tgt = build_target_hamiltonian(args.target_system, args.n_input,
                                       args.target_seed,
                                       xxz_delta=args.xxz_delta,
                                       disorder=args.target_disorder)
    psi0 = np.ones(2 ** args.n_input, dtype=complex) / np.sqrt(2 ** args.n_input)
    times = np.linspace(0, args.t_max, args.n_steps)
    t0 = time.time()
    psi_t = evolve_states(H_tgt, psi0, times)
    print(f"  Evolved {args.n_steps} state-vector steps in {time.time()-t0:.1f}s")

    # ---- Target observable: k-body X string on input state ----
    k = args.target_body
    target_op_in = np.eye(2 ** args.n_input, dtype=complex)
    s = ["I"] * args.n_input
    for i in range(min(k, args.n_input)):
        s[i] = "X"
    target_op_in = pauli_string("".join(s))
    y_target = np.array([float(np.real(psi.conj() @ (target_op_in @ psi)))
                           for psi in psi_t])[:, None]    # (T, 1)
    print(f"  Target ranges {y_target.min():.3f}..{y_target.max():.3f}, "
            f"std={y_target.std():.3f}")

    # ---- Per-seed evaluation ----
    method_results = {
        "QRC_state_injection": [],
        "Classical_shadows_RFF": [],
        "Cheating_classical_RFF": [],
        "Cheating_classical_ESN": [],
    }
    feat_dims = {}
    for seed in range(args.n_seeds):
        print(f"\n=== seed {seed} ===")
        rng_qrc = np.random.default_rng(1000 + seed)
        rng_shadow = np.random.default_rng(2000 + seed)
        H_tfim = tfim_hamiltonian(args.n_qubits, J=1.0, g=1.0)

        # QRC
        t0 = time.time()
        qrc_step, qrc_D = make_state_injection_qrc(
            args.n_qubits, args.n_input, H_tfim,
            shots_per_qubit=args.shots_per_qubit, rng=rng_qrc)
        feats_qrc = np.array([qrc_step(psi_t[t]) for t in range(args.n_steps)])
        feat_dims["QRC_state_injection"] = qrc_D
        Fw_qrc = windowed_features(feats_qrc, args.window)
        r = _eval_windowed_no_window(Fw_qrc, y_target[args.window:],
                                        args.horizons, args.train_frac, seed)
        print(f"  QRC ({time.time()-t0:.1f}s, D={qrc_D}): "
                f"k1={r['k1_nrmse']:.3f}  k5={r['k5_nrmse']:.3f}  "
                f"k20={r['k20_nrmse']:.3f}")
        method_results["QRC_state_injection"].append(r)

        # Shadows + RFF
        t0 = time.time()
        shadow_step, shadow_D = make_shadow_extractor(
            args.n_input, args.shots_per_qubit, args.n_qubits, rng_shadow,
            include_2body=True)
        feats_shadow = np.array([shadow_step(psi_t[t])
                                    for t in range(args.n_steps)])
        feat_dims["Classical_shadows_RFF"] = shadow_D
        Fw_shadow_inputs = windowed_features(feats_shadow, args.window)
        # RFF on the shadow features, matched to QRC effective dim D_eff
        D_eff_qrc = args.window * qrc_D
        rff_feats = rff_features(Fw_shadow_inputs, D_eff_qrc, seed)
        r = _eval_windowed_no_window(rff_feats, y_target[args.window:],
                                        args.horizons, args.train_frac, seed)
        print(f"  Shadows+RFF ({time.time()-t0:.1f}s, D_in={shadow_D},"
                f" D_rff={D_eff_qrc}): k1={r['k1_nrmse']:.3f}  "
                f"k5={r['k5_nrmse']:.3f}  k20={r['k20_nrmse']:.3f}")
        method_results["Classical_shadows_RFF"].append(r)

        # Cheating classical + RFF (exact local Paulis, no shots)
        t0 = time.time()
        cheat_step, cheat_D = make_cheating_classical_extractor(
            args.n_input, include_2body=True)
        feats_cheat = np.array([cheat_step(psi_t[t])
                                  for t in range(args.n_steps)])
        feat_dims["Cheating_classical_RFF"] = cheat_D
        Fw_cheat_inputs = windowed_features(feats_cheat, args.window)
        rff_feats_cheat = rff_features(Fw_cheat_inputs, D_eff_qrc, seed)
        r = _eval_windowed_no_window(rff_feats_cheat, y_target[args.window:],
                                        args.horizons, args.train_frac, seed)
        print(f"  Cheat+RFF  ({time.time()-t0:.1f}s, D_in={cheat_D},"
                f" D_rff={D_eff_qrc}): k1={r['k1_nrmse']:.3f}  "
                f"k5={r['k5_nrmse']:.3f}  k20={r['k20_nrmse']:.3f}")
        method_results["Cheating_classical_RFF"].append(r)

        # Cheating classical + ESN
        t0 = time.time()
        W_in, W_res, leak = make_esn(cheat_D, D_eff_qrc, seed)
        acts = esn_run(feats_cheat, W_in, W_res, leak)
        Fw_esn = windowed_features(acts, args.window)
        r = _eval_windowed_no_window(Fw_esn, y_target[args.window:],
                                        args.horizons, args.train_frac, seed)
        print(f"  Cheat+ESN  ({time.time()-t0:.1f}s, N={D_eff_qrc}): "
                f"k1={r['k1_nrmse']:.3f}  k5={r['k5_nrmse']:.3f}  "
                f"k20={r['k20_nrmse']:.3f}")
        method_results["Cheating_classical_ESN"].append(r)

    # ---- Summary ----
    summary = {"args": vars(args),
                "feature_dims": feat_dims,
                "methods": method_results,
                "per_method_means": {}}
    for method, runs in method_results.items():
        means = {}
        for k_ in args.horizons:
            vals = [r[f"k{k_}_nrmse"] for r in runs]
            means[f"k{k_}_mean"] = float(np.nanmean(vals))
            means[f"k{k_}_std"] = float(np.nanstd(vals))
        means["kappa_mean"] = float(np.nanmean([r["kappa"] for r in runs]))
        summary["per_method_means"][method] = means
    out_json = out_dir / "summary.json"
    with open(out_json, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"\nSaved {out_json}")

    print(f"\n=== Mean test NRMSE across {args.n_seeds} seeds ===")
    print(f"{'method':<26}  " + "  ".join([f"k={h:<3}" for h in args.horizons]))
    for method, m in summary["per_method_means"].items():
        row = f"{method:<26}  " + "  ".join(
            [f"{m[f'k{h}_mean']:.3f}+/-{m[f'k{h}_std']:.3f}"
              for h in args.horizons])
        print(row)


if __name__ == "__main__":
    main()
