#!/usr/bin/env python3
"""
run_quantum_state_input.py - Paper 6 main experiment.

QRC vs classical reservoirs on a HILBERT-SPACE INPUT task.  The input
is itself a q-qubit quantum state |psi_t> generated by a fixed
Hamiltonian trajectory; the classical baseline cannot encode |psi_t>
into a feature vector without first burning shots on shadow tomography.
QRC uses the same shot budget to do encoding + reservoir mixing
simultaneously.

Methods (matched shot budget M = shots_per_qubit * q per timestep):
  - QRC_state_injection : on each step, |psi_t> is prepared on the
       first n_in reservoir qubits; rest in |0>.  Evolve under H_TFIM(q)
       for time tau.  Sample M shots, extract local Paulis
       (<Z_i>, <Z_i Z_j>).
  - Classical_shadows + RFF : on each step, perform M random Clifford
       shadow snapshots on |psi_t>; estimate local Paulis from shadows.
       Use as features for windowed RFF.
  - Cheating_classical + RFF : exact local Paulis on |psi_t> (no shot
       noise).  Upper bound for any classical method using local Paulis.
  - ESN_matched : ESN at matched N on the cheating Pauli features.

Target functionals (paper 6 cleanest target = 4-body Pauli):
  - <X_0 X_1 X_2 X_3> on the input state at horizon t+k
       Shadow shot cost for k-body observables grows as 3^k, so QRC's
       fixed sigma ~ 1/sqrt(M) should beat shadows badly at q >> n_in.

Outputs:  results/quantum_state_input/<tag>/summary.json + plots
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import warnings
from pathlib import Path

import numpy as np
from scipy import linalg as sla

warnings.filterwarnings("ignore")

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

# Reuse Pauli + Hamiltonian + Heisenberg builders from paper-5 script
from run_quantum_input_experiment import (
    I2, X, Y, Z, PAULI,
    pauli_string, single_site, two_site,
    heisenberg_chain_hamiltonian, xxz_chain_hamiltonian,
    build_target_hamiltonian, evolve_states,
    tfim_hamiltonian, scrambling_hamiltonian,
    _apply_single_qubit_gate,
    make_esn, esn_run, rff_features,
    ridge_solve, windowed_features, feature_gram_condition,
)


def eval_multitarget(F: np.ndarray, y: np.ndarray,
                       horizons: list[int], train_frac: float,
                       alpha: float = 1.0) -> dict:
    """Train ridge readout, return per-target NRMSE arrays.

    F: (T_feat, D) features.  y: (T_feat, K) targets (already aligned).
    Output dict has 'k{h}_per_target_nrmse' = array of K NRMSEs and
    'k{h}_mean_nrmse', 'k{h}_median_nrmse'.
    """
    T, K = y.shape
    n_train = int(round(train_frac * T))
    out = {"n_features": F.shape[1], "n_train": n_train, "n_targets": K,
            "kappa": feature_gram_condition(F[:n_train], alpha=alpha)}
    for h in horizons:
        if T - h <= n_train + 5:
            out[f"k{h}_mean_nrmse"] = float("nan")
            continue
        F_tr = F[:n_train - h]
        y_tr = y[h:n_train]
        F_te = F[n_train:T - h]
        y_te = y[n_train + h:T]
        W = ridge_solve(F_tr, y_tr, alpha=alpha)
        y_pred = F_te @ W
        # Per-target NRMSE
        rmse_per = np.sqrt(np.mean((y_pred - y_te) ** 2, axis=0))
        std_per = np.std(y_te, axis=0)
        nrmse_per = rmse_per / (std_per + 1e-12)
        out[f"k{h}_per_target_nrmse"] = nrmse_per.tolist()
        out[f"k{h}_mean_nrmse"] = float(np.mean(nrmse_per))
        out[f"k{h}_median_nrmse"] = float(np.median(nrmse_per))
    return out


def _eval_windowed_no_window(F, y_aligned, horizons, train_frac, seed):
    """Single-target NRMSE (back-compat for pauli/renyi2 modes)."""
    T = len(F)
    n_train = int(round(train_frac * T))
    results = {"kappa": feature_gram_condition(F[:n_train], alpha=1.0),
                "n_features": F.shape[1], "n_train": n_train}
    for h in horizons:
        if T - h <= n_train + 5:
            results[f"k{h}_nrmse"] = float("nan"); continue
        F_tr = F[:n_train - h]
        y_tr = y_aligned[h:n_train]
        F_te = F[n_train:T - h]
        y_te = y_aligned[n_train + h:T]
        W = ridge_solve(F_tr, y_tr, alpha=1.0)
        y_pred = F_te @ W
        rmse = float(np.sqrt(np.mean((y_pred - y_te) ** 2)))
        std = float(np.std(y_te))
        results[f"k{h}_nrmse"] = rmse / (std + 1e-12)
    return results


# ---------------------------------------------------------------------------
# State-injection QRC
# ---------------------------------------------------------------------------

def make_state_injection_qrc(n_qubits: int, n_in: int, H_reservoir: np.ndarray,
                                tau: float = 1.0,
                                shots_per_qubit: int = 1024,
                                rng: np.random.Generator | None = None):
    """Build a QRC with state-injection input mode.

    At each timestep:
      1. Receive a 2^n_in-dim input state vector psi_in.
      2. Prepare on reservoir: |psi_in> tensor |0>^(q-n_in).
      3. Evolve full reservoir under H_reservoir for time tau.
      4. Sample M = shots_per_qubit * q shots.  Extract local Paulis
         (<Z_i>, <Z_i Z_j>), D = q(q+1)/2 features.
    NO recurrence across timesteps (input state is re-prepared each step
    -- same constraint as the classical baseline; the only memory comes
    from windowing the features later, identical for both methods).
    """
    dim = 2 ** n_qubits
    q = n_qubits
    M = shots_per_qubit * q
    U_evolve = sla.expm(-1j * H_reservoir * tau)
    if rng is None:
        rng = np.random.default_rng(0)

    idx = np.arange(dim, dtype=np.uint32)
    bits = ((idx[:, None] >> np.arange(q)[::-1]) & 1).astype(np.int8)
    signs = (1 - 2 * bits).astype(np.float64)
    iu, ju = np.triu_indices(q, k=1)
    pair_signs = signs[:, iu] * signs[:, ju]

    dim_in = 2 ** n_in
    dim_rest = 2 ** (q - n_in)
    rest_init = np.zeros(dim_rest, dtype=complex); rest_init[0] = 1.0

    def step(psi_in: np.ndarray) -> np.ndarray:
        """Inject |psi_in> on first n_in qubits, evolve, sample, return features."""
        psi_full = np.kron(psi_in, rest_init)
        psi_full = U_evolve @ psi_full
        p = np.abs(psi_full) ** 2
        s = p.sum()
        if s > 0:
            p = p / s
        counts = rng.multinomial(M, p).astype(np.float64)
        w = counts / M
        Z_vals  = w @ signs
        ZZ_vals = w @ pair_signs
        return np.concatenate([Z_vals, ZZ_vals])

    return step, q * (q + 1) // 2


# ---------------------------------------------------------------------------
# Classical shadow tomography
# ---------------------------------------------------------------------------

# Single-qubit Clifford rotations that map computational basis to X/Y/Z basis.
# We use the 3-basis (Pauli) shadow scheme (simplest, well-known).
# Rotation that maps measurement basis to X-eigenstates: H (Hadamard)
# To Y-eigenstates: HS^dag (or equivalently S H), depending on convention.
# To Z-eigenstates: identity.
H_GATE = (1.0 / np.sqrt(2)) * np.array([[1, 1], [1, -1]], dtype=complex)
S_DAG = np.array([[1, 0], [0, -1j]], dtype=complex)
HSDAG = H_GATE @ S_DAG  # rotates Y eigenstates to Z basis


def _rotated_probabilities(psi: np.ndarray, n: int,
                              basis_pattern: tuple[int, ...]) -> np.ndarray:
    """Probability distribution of measuring |psi> in basis given by
    basis_pattern, a length-n tuple of (0=X, 1=Y, 2=Z)."""
    BASIS_GATES = [H_GATE, HSDAG, I2]
    psi_rot = psi
    for qubit in range(n):
        b = basis_pattern[qubit]
        if b != 2:                      # Z = identity rotation
            psi_rot = _apply_single_qubit_gate(psi_rot, n, qubit, BASIS_GATES[b])
    p = np.abs(psi_rot) ** 2
    s = p.sum()
    return p / s if s > 0 else p


def shadow_snapshots_estimate(psi: np.ndarray, n: int, M: int,
                                 rng: np.random.Generator,
                                 want_features: list[tuple[str, ...]]
                                ) -> np.ndarray:
    """Estimate Pauli expectations from M Pauli-shadow snapshots of |psi>
    using the Huang-Kueng-Preskill (2020) single-qubit-Clifford protocol.

    FAST VERSION: shots are grouped by basis pattern.  Cost is
    O(3^n * 2^n * n + M * n) instead of O(M * 2^n * n) -- ~80x speedup
    for n=4, M=7168.
    """
    PAULI_CODE = {"X": 0, "Y": 1, "Z": 2}

    # Sample M basis patterns at once.
    bases_M = rng.integers(0, 3, size=(M, n), dtype=np.int8)   # (M, n)
    # Pack each pattern into a single integer key in [0, 3^n).
    keys = np.zeros(M, dtype=np.int64)
    for q_ in range(n):
        keys = keys * 3 + bases_M[:, q_]
    # Unique patterns + counts; sort by key for grouped processing.
    order = np.argsort(keys, kind="stable")
    keys_sorted = keys[order]
    bases_sorted = bases_M[order]
    # Find group boundaries.
    boundaries = np.flatnonzero(np.diff(keys_sorted)) + 1
    starts = np.concatenate([[0], boundaries])
    ends   = np.concatenate([boundaries, [M]])

    # We'll fill outcomes (M, n) in the SORTED order, then unsort.
    outcomes_sorted = np.zeros((M, n), dtype=np.int8)
    dim = 2 ** n
    bit_shifts = (n - 1 - np.arange(n)).astype(np.int64)
    for gi in range(len(starts)):
        s_, e_ = starts[gi], ends[gi]
        pattern = tuple(int(b) for b in bases_sorted[s_])    # all same in group
        p = _rotated_probabilities(psi, n, pattern)
        # Sample (e_ - s_) outcomes from this distribution via multinomial:
        # represent as a count vector over the 2^n outcomes, then expand to
        # a list of sample indices (faster than rng.choice per shot).
        counts = rng.multinomial(e_ - s_, p)
        # Build a flat array of sample integer indices respecting counts.
        sample_ints = np.repeat(np.arange(dim, dtype=np.int64), counts)
        rng.shuffle(sample_ints)            # randomize within the group
        # Unpack to bits, MSB-first.
        bits = ((sample_ints[:, None] >> bit_shifts) & 1).astype(np.int8)
        outcomes_sorted[s_:e_, :] = bits

    # Unsort to recover original shot order
    inv_order = np.empty_like(order); inv_order[order] = np.arange(M)
    outcomes = outcomes_sorted[inv_order]

    # +/-1 eigenvalues
    eig = (1 - 2 * outcomes).astype(np.float64)               # (M, n)

    out = np.zeros(len(want_features))
    for fi, feat in enumerate(want_features):
        pairs = [(feat[i], feat[i + 1]) for i in range(0, len(feat), 2)]
        kbody = len(pairs)
        match = np.ones(M, dtype=bool)
        prod_eig = np.ones(M, dtype=np.float64)
        for (lbl, site) in pairs:
            match &= (bases_M[:, site] == PAULI_CODE[lbl])
            prod_eig *= eig[:, site]
        contribs = np.where(match, (3.0 ** kbody) * prod_eig, 0.0)
        out[fi] = contribs.mean()
    return out


def make_shadow_extractor(n_in: int, shots_per_qubit_total: int,
                            q_reservoir: int,
                            rng: np.random.Generator,
                            include_2body: bool = True,
                            mode: str = "noise_model"):
    """Build a feature extractor estimating local Paulis of |psi_in> from
    M = shots_per_qubit_total * q_reservoir Pauli-shadow shots.

    mode='snapshots' : true per-shot simulation (exact, slow, O(M * 2^n_in * n_in)
                       per timestep; only tractable for n_in <= ~6).
    mode='noise_model': analytical -- compute exact <P> and add iid Gaussian
                       noise with the Pauli-shadow per-feature variance
                       Var[<P>_est] = (3^|P| - <P>^2) / M
                       (Huang-Kueng-Preskill 2020, single-qubit Clifford
                       protocol).  Matches per-feature variance to first
                       order; cross-feature covariance is small for
                       most Pauli pairs.  ~100x faster at n_in >= 8.
    """
    M = shots_per_qubit_total * q_reservoir
    want_specs = []        # (pauli_label, sites_tuple)
    want_ops = []           # the corresponding Pauli operator on n_in qubits
    for i in range(n_in):
        for plabel in ("Z", "X", "Y"):
            want_specs.append((plabel, (i,)))
            want_ops.append(single_site(plabel, i, n_in))
    if include_2body:
        for i in range(n_in):
            for j in range(i + 1, n_in):
                for plabel in ("Z", "X", "Y"):
                    want_specs.append((plabel, (i, j)))
                    want_ops.append(two_site(plabel, i, plabel, j, n_in))
    want_weights = np.array([len(s[1]) for s in want_specs])      # |P|
    var_factors = (3.0 ** want_weights) / M                          # 3^|P| / M

    if mode == "snapshots":
        # Legacy slow path (kept for sanity-check on small n_in).
        want_tuples = []
        for (plabel, sites) in want_specs:
            t = []
            for s in sites:
                t.extend([plabel, s])
            want_tuples.append(tuple(t))

        def step(psi_in):
            return shadow_snapshots_estimate(psi_in, n_in, M, rng, want_tuples)

        return step, len(want_specs)

    if mode != "noise_model":
        raise ValueError(f"Unknown shadow mode: {mode}")

    def step(psi_in: np.ndarray) -> np.ndarray:
        # Exact Pauli expectations
        exact = np.empty(len(want_ops))
        for k, O in enumerate(want_ops):
            exact[k] = float(np.real(psi_in.conj() @ (O @ psi_in)))
        # Per-feature variance bound (use 3^|P|/M; the -<P>^2 term only
        # tightens it, so this is slightly conservative for shadows).
        sigma = np.sqrt(np.maximum(var_factors - exact ** 2 / M, var_factors / 2))
        # Actually: keep Var = 3^|P|/M (true upper-bound estimator variance),
        # which is the worst-case classical-shadow guarantee.
        sigma = np.sqrt(var_factors)
        noise = rng.standard_normal(len(want_ops)) * sigma
        return exact + noise

    return step, len(want_specs)


def make_cheating_classical_extractor(n_in: int, include_2body: bool = True):
    """Exact local Pauli features on |psi_in>, no shot noise."""
    want = []
    ops = []
    for i in range(n_in):
        for p in ("Z", "X", "Y"):
            want.append((p, i))
            ops.append(single_site(p, i, n_in))
    if include_2body:
        for i in range(n_in):
            for j in range(i + 1, n_in):
                for p in ("Z", "X", "Y"):
                    want.append((p, i, p, j))
                    ops.append(two_site(p, i, p, j, n_in))

    def step(psi_in: np.ndarray) -> np.ndarray:
        out = np.empty(len(ops))
        for k, O in enumerate(ops):
            out[k] = float(np.real(psi_in.conj() @ (O @ psi_in)))
        return out

    return step, len(want)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--n-input", type=int, default=5,
                    help="qubits of the input quantum state")
    p.add_argument("--n-qubits", type=int, default=8,
                    help="qubits in the QRC reservoir (>= n-input)")
    p.add_argument("--target-system", choices=["heisenberg", "xxz"],
                    default="heisenberg")
    p.add_argument("--target-seed", type=int, default=42)
    p.add_argument("--target-disorder", type=float, default=0.5)
    p.add_argument("--xxz-delta", type=float, default=0.5)
    p.add_argument("--n-steps", type=int, default=600)
    p.add_argument("--t-max", type=float, default=60.0)
    p.add_argument("--window", type=int, default=5)
    p.add_argument("--horizons", type=int, nargs="+", default=[1, 5, 20])
    p.add_argument("--n-seeds", type=int, default=3)
    p.add_argument("--train-frac", type=float, default=0.7)
    p.add_argument("--shots-per-qubit", type=int, default=1024)
    p.add_argument("--reservoir", choices=["tfim", "scram"], default="tfim",
                    help="QRC reservoir Hamiltonian (TFIM nearest-neighbour "
                          "or SYK-style all-to-all scrambling)")
    p.add_argument("--tau", type=float, default=1.0,
                    help="Reservoir evolution time per timestep (larger tau "
                          "= more scrambling)")
    p.add_argument("--target-body", type=int, default=4,
                    help="body count k of the target Pauli string"
                          " (target = <X_0 X_1 ... X_{k-1}>)")
    p.add_argument("--target-type",
                    choices=["pauli", "renyi2", "multipauli"],
                    default="pauli",
                    help="pauli: <X_0..X_{k-1}>(t+horizon).  renyi2: "
                          "S_2(rho_A) where A = first n_input//2 qubits. "
                          "multipauli: BATCH of all 1-body and 2-body "
                          "same-letter Paulis on input -- the Innocenti "
                          "et al. niche, where QRC's single feature batch "
                          "amortizes across many targets while shadows "
                          "pay variance per target.")
    p.add_argument("--out-dir", type=str,
                    default=str(ROOT / "results" / "quantum_state_input"))
    args = p.parse_args()

    assert args.n_input <= args.n_qubits, "n_input <= n_qubits"
    out_dir = Path(args.out_dir); out_dir.mkdir(parents=True, exist_ok=True)

    print(f"=== Paper 6 task: {args.n_input}-qubit input state -> "
            f"{args.n_qubits}-qubit reservoir ===")
    print(f"    target: {args.target_body}-body Pauli <X_0..X_{args.target_body-1}>"
            f" at horizons {args.horizons}")
    print(f"    shots = {args.shots_per_qubit * args.n_qubits} per timestep "
            f"(shared by QRC and shadows)")

    # ---- Generate input quantum-state trajectory ----
    H_tgt = build_target_hamiltonian(args.target_system, args.n_input,
                                       args.target_seed,
                                       xxz_delta=args.xxz_delta,
                                       disorder=args.target_disorder)
    psi0 = np.ones(2 ** args.n_input, dtype=complex) / np.sqrt(2 ** args.n_input)
    times = np.linspace(0, args.t_max, args.n_steps)
    t0 = time.time()
    psi_t = evolve_states(H_tgt, psi0, times)
    print(f"  Evolved {args.n_steps} state-vector steps in {time.time()-t0:.1f}s")

    # ---- Target functional on input state ----
    if args.target_type == "pauli":
        k = args.target_body
        s = ["I"] * args.n_input
        for i in range(min(k, args.n_input)):
            s[i] = "X"
        target_op_in = pauli_string("".join(s))
        y_target = np.array([float(np.real(psi.conj() @ (target_op_in @ psi)))
                               for psi in psi_t])[:, None]
        target_desc = f"<{''.join(s)}>"
    elif args.target_type == "multipauli":
        # Batch: all 1-body Paulis (3*n) + all 2-body same-letter (3*n*(n-1)/2)
        target_ops_list = []
        target_labels = []
        for i in range(args.n_input):
            for plabel in ("X", "Y", "Z"):
                target_ops_list.append(single_site(plabel, i, args.n_input))
                target_labels.append(f"{plabel}_{i}")
        for i in range(args.n_input):
            for j in range(i + 1, args.n_input):
                for plabel in ("X", "Y", "Z"):
                    target_ops_list.append(
                        two_site(plabel, i, plabel, j, args.n_input))
                    target_labels.append(f"{plabel}_{i}{plabel}_{j}")
        K = len(target_ops_list)
        y_target = np.zeros((args.n_steps, K))
        for ti, psi in enumerate(psi_t):
            for ki, O in enumerate(target_ops_list):
                y_target[ti, ki] = float(np.real(psi.conj() @ (O @ psi)))
        target_desc = (f"BATCH of K={K} input observables (1-body + "
                        f"2-body same-letter Paulis)")
    elif args.target_type == "renyi2":
        # S_2(rho_A) = -log Tr(rho_A^2);  rho_A = partial-trace over first
        # n_input//2 qubits.  Computed via Schmidt SVD of |psi> reshaped.
        nA = args.n_input // 2
        nB = args.n_input - nA
        y_list = []
        for psi in psi_t:
            psi_mat = psi.reshape((2 ** nA, 2 ** nB))
            svals = np.linalg.svd(psi_mat, compute_uv=False)
            p2 = (svals ** 2)
            p2 = p2[p2 > 1e-14]
            purity = float(np.sum(p2 ** 2))
            y_list.append(-np.log(max(purity, 1e-14)))
        y_target = np.array(y_list)[:, None]
        target_desc = f"S_2(rho_A), A = first {nA} qubits"
    else:
        raise ValueError(args.target_type)
    print(f"  Target = {target_desc};  range "
            f"{y_target.min():.3f}..{y_target.max():.3f}, "
            f"std={y_target.std():.3f}")

    # ---- Per-seed evaluation ----
    method_results = {
        "QRC_state_injection": [],
        "Classical_shadows_RFF": [],
        "Classical_shadows_ESN": [],
        "Cheating_classical_RFF": [],
        "Cheating_classical_ESN": [],
    }
    feat_dims = {}
    is_multitarget = (args.target_type == "multipauli")
    EVAL = (lambda F, y, hz, tf, sd:
              eval_multitarget(F, y, hz, tf)) if is_multitarget else \
            (lambda F, y, hz, tf, sd:
              _eval_windowed_no_window(F, y, hz, tf, sd))
    METRIC_KEY = "k{}_mean_nrmse" if is_multitarget else "k{}_nrmse"
    def _fmt(r):
        return "  ".join([f"k{h}={r[METRIC_KEY.format(h)]:.3f}"
                            for h in args.horizons])

    for seed in range(args.n_seeds):
        print(f"\n=== seed {seed} ===")
        rng_qrc = np.random.default_rng(1000 + seed)
        rng_shadow = np.random.default_rng(2000 + seed)
        if args.reservoir == "tfim":
            H_res = tfim_hamiltonian(args.n_qubits, J=1.0, g=1.0)
        else:
            H_res = scrambling_hamiltonian(args.n_qubits, seed=seed)

        # QRC
        t0 = time.time()
        qrc_step, qrc_D = make_state_injection_qrc(
            args.n_qubits, args.n_input, H_res, tau=args.tau,
            shots_per_qubit=args.shots_per_qubit, rng=rng_qrc)
        feats_qrc = np.array([qrc_step(psi_t[t]) for t in range(args.n_steps)])
        feat_dims["QRC_state_injection"] = qrc_D
        Fw_qrc = windowed_features(feats_qrc, args.window)
        r = EVAL(Fw_qrc, y_target[args.window:], args.horizons,
                  args.train_frac, seed)
        print(f"  QRC ({time.time()-t0:.1f}s, D={qrc_D}): {_fmt(r)}")
        method_results["QRC_state_injection"].append(r)

        # Shadows + RFF
        t0 = time.time()
        shadow_step, shadow_D = make_shadow_extractor(
            args.n_input, args.shots_per_qubit, args.n_qubits, rng_shadow,
            include_2body=True)
        feats_shadow = np.array([shadow_step(psi_t[t])
                                    for t in range(args.n_steps)])
        feat_dims["Classical_shadows_RFF"] = shadow_D
        Fw_shadow_inputs = windowed_features(feats_shadow, args.window)
        D_eff_qrc = args.window * qrc_D
        rff_feats = rff_features(Fw_shadow_inputs, D_eff_qrc, seed)
        r = EVAL(rff_feats, y_target[args.window:], args.horizons,
                  args.train_frac, seed)
        print(f"  Shadows+RFF ({time.time()-t0:.1f}s, D_in={shadow_D},"
                f" D_rff={D_eff_qrc}): {_fmt(r)}")
        method_results["Classical_shadows_RFF"].append(r)

        # Shadows + ESN (shot-noisy shadow features, ESN readout) -- the
        # fair shot-matched classical baseline with nonlinear readout.
        t0 = time.time()
        W_in_s, W_res_s, leak_s = make_esn(shadow_D, D_eff_qrc, seed)
        acts_shadow = esn_run(feats_shadow, W_in_s, W_res_s, leak_s)
        Fw_shadow_esn = windowed_features(acts_shadow, args.window)
        r = EVAL(Fw_shadow_esn, y_target[args.window:], args.horizons,
                  args.train_frac, seed)
        print(f"  Shadows+ESN ({time.time()-t0:.1f}s, N={D_eff_qrc}): {_fmt(r)}")
        method_results["Classical_shadows_ESN"].append(r)

        # Cheating classical + RFF (exact local Paulis, no shots)
        t0 = time.time()
        cheat_step, cheat_D = make_cheating_classical_extractor(
            args.n_input, include_2body=True)
        feats_cheat = np.array([cheat_step(psi_t[t])
                                  for t in range(args.n_steps)])
        feat_dims["Cheating_classical_RFF"] = cheat_D
        Fw_cheat_inputs = windowed_features(feats_cheat, args.window)
        rff_feats_cheat = rff_features(Fw_cheat_inputs, D_eff_qrc, seed)
        r = EVAL(rff_feats_cheat, y_target[args.window:], args.horizons,
                  args.train_frac, seed)
        print(f"  Cheat+RFF  ({time.time()-t0:.1f}s, D_in={cheat_D},"
                f" D_rff={D_eff_qrc}): {_fmt(r)}")
        method_results["Cheating_classical_RFF"].append(r)

        # Cheating classical + ESN
        t0 = time.time()
        W_in, W_res, leak = make_esn(cheat_D, D_eff_qrc, seed)
        acts = esn_run(feats_cheat, W_in, W_res, leak)
        Fw_esn = windowed_features(acts, args.window)
        r = EVAL(Fw_esn, y_target[args.window:], args.horizons,
                  args.train_frac, seed)
        print(f"  Cheat+ESN  ({time.time()-t0:.1f}s, N={D_eff_qrc}): {_fmt(r)}")
        method_results["Cheating_classical_ESN"].append(r)

    # ---- Summary ----
    summary = {"args": vars(args),
                "feature_dims": feat_dims,
                "methods": method_results,
                "per_method_means": {}}
    metric_key = "k{}_mean_nrmse" if is_multitarget else "k{}_nrmse"
    for method, runs in method_results.items():
        means = {}
        for k_ in args.horizons:
            vals = [r[metric_key.format(k_)] for r in runs]
            means[f"k{k_}_mean"] = float(np.nanmean(vals))
            means[f"k{k_}_std"] = float(np.nanstd(vals))
        means["kappa_mean"] = float(np.nanmean([r["kappa"] for r in runs]))
        summary["per_method_means"][method] = means
    out_json = out_dir / "summary.json"
    with open(out_json, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"\nSaved {out_json}")

    print(f"\n=== Mean test NRMSE across {args.n_seeds} seeds "
            f"({'mean-over-K-targets' if is_multitarget else 'single target'}) ===")
    print(f"{'method':<26}  " + "  ".join([f"k={h:<3}" for h in args.horizons]))
    for method, m in summary["per_method_means"].items():
        row = f"{method:<26}  " + "  ".join(
            [f"{m[f'k{h}_mean']:.3f}+/-{m[f'k{h}_std']:.3f}"
              for h in args.horizons])
        print(row)

    if is_multitarget:
        # Per-target breakdown: median NRMSE per method at k=1
        print(f"\n=== Per-target NRMSE at k=1 (seed 0 only, for inspection) ===")
        print(f"{'target':<14}  " + "  ".join(
            [f"{m:<18}" for m in method_results.keys()]))
        per_method_arrs = {m: np.array(runs[0]["k1_per_target_nrmse"])
                              for m, runs in method_results.items()}
        for ki, lbl in enumerate(target_labels):
            row = f"{lbl:<14}  " + "  ".join(
                [f"{per_method_arrs[m][ki]:<18.3f}"
                  for m in method_results.keys()])
            print(row)


if __name__ == "__main__":
    main()
